
resources_path: "resources"
font: "MesloLGS NF Regular.ttf"


homemonitor:
  refresh_period: 60
  fields_configuration: 
    weather:
      influxdb_connector: homemonitor
      measurement: openweather_current_weather
      fields:
        temperature: temp
        humidity: humidity
        wind_speed: wind_speed
        weather_description: weather_description
    salon:
      influxdb_connector: homemonitor
      measurement: bme688
      fields: 
        temperature: temperature
        humidity: humidity
    cuisine:
      influxdb_connector: pi
      measurement: bme280
      fields:
        temperature: temperature
        humidity: humidity
    elec:
      influxdb_connector: pi
      measurement: teleinfo
      fields:
        app_power: PAPP

dayweather:
  refresh_period: 60
  gps_coordinates: [48.85, 2.35]

citiesweather:
  refresh_period: 60
  cities:
    - "Carnac, FR"
    - "Peisey-Nancroix, FR"
    - "Avignon, FR"
    - "New York, US"

elecconsumption:
  refresh_period: 60
  fields_configuration:
    influxdb_connector: pi
    measurement: teleinfo
    fields:
      app_power: PAPP
      total_power: BASE 

sysmonitor:
  refresh_period: 60
  fields_configuration:
    pi:
      cpu_usage:
        measurement: system_2
        field: cpu_usage
      ram_usage:
        measurement: system_2
        field: ram_usage
      mem_usage: 
        measurement: system_1
        field: mem_usage
        max_value: 29
      cpu_temp: 
        measurement: system_1
        field: cpu_temperature
        max_value: 85
    homemonitor:
      cpu_usage:
        measurement: system_hm_2
        field: cpu_usage
      ram_usage:
        measurement: system_hm_2
        field: ram_usage
      mem_usage: 
        measurement: system_hm_1
        field: mem_usage
        max_value: 30
      cpu_temp: 
        measurement: system_hm_1
        field: cpu_temperature
        max_value: 85
