title: "Maison Avignon"

temperature_thresholds: &temperature_thresholds
  18: blue
  22: green
  26: orange
  50: red

humidity_thresholds: &humidity_thresholds
  0.2: red
  0.4: orange
  0.6: green
  0.8: blue
  1: purple

outside_temperature_thresholds: &outside_temperature_thresholds
  5: blue
  15: green
  25: orange
  100: red

cpu_thresholds: &cpu_thresholds
  0.2: blue
  0.4: green
  0.6: yellow
  0.8: orange
  1: red 

pi_temp_thresholds: &pi_temp_thresholds
  0.3: blue
  0.5: green
  0.7: yellow
  0.9: orange
  1: red

memory_thresholds: &memory_thresholds
  0.2: blue
  0.4: green
  0.6: yellow
  0.8: orange
  1: red 

indicators_parameters:
  window_size: 10m

layouts:
  - title: "Capteurs entree"
    influxdb_connector: homemonitor
    indicators:
      - type: number
        name: "Température"
        measurement: bme280
        field: temperature
        refresh_rate: 120s
        thresholds: *temperature_thresholds
        string_format: "{value:.1f}°C"
      - type: gauge
        name: "Humidité"
        measurement: bme280
        field: humidity
        refresh_rate: 120s
        bounds: [0, 100]
        thresholds: *humidity_thresholds
        format_suffix: "%"
      - type: number
        name: Pression
        measurement: bme280
        field: pressure
        refresh_rate: 120s
        string_format: "{value:.4f} Bar"
        math_operation: !math_op ["/", 1000]
  - title: "Capteurs chambre Thibault"
    influxdb_connector: pizero
    indicators:
      - type: number
        name: "Température"
        measurement: bme280
        field: temperature
        refresh_rate: 120s
        thresholds: *temperature_thresholds
        string_format: "{value:.1f}°C"
      - type: gauge
        name: "Humidité"
        measurement: bme280
        field: humidity
        refresh_rate: 120s
        bounds: [0, 100]
        thresholds: *humidity_thresholds
        format_suffix: "%"
      - type: number
        name: Pression
        measurement: bme280
        field: pressure
        refresh_rate: 120s
        string_format: "{value:.4f} Bar"
        math_operation: !math_op ["/", 1000]
  - title: "Météo extérieur"
    influxdb_connector: homemonitor
    indicators:
      - type: number
        name: "Température"
        measurement: openweather_current_weather
        field: temp
        refresh_rate: 10m
        thresholds: *outside_temperature_thresholds
        string_format: "{value:.1f}°C"
      - type: gauge
        name: "Humidité"
        measurement: openweather_current_weather
        field: humidity
        refresh_rate: 10m
        bounds: [0, 100]
        thresholds: *humidity_thresholds
        format_suffix: "%"
      - type: number
        name: "Vent"
        measurement: openweather_current_weather
        field: wind_speed
        refresh_rate: 10m
        string_format: "{value:.1f} km/h"
        math_operation: !math_op ["*", 3.6]
      - type: weather_icon
        measurement: openweather_current_weather
        field: weather_description
        refresh_rate: 10m

  - title: "Pi entree"
    influxdb_connector: homemonitor
    indicators:
      - type: gauge
        name: "CPU"
        measurement: system_hm_2
        field: cpu_usage
        refresh_rate: 1m
        bounds: [0, 100]
        thresholds: *cpu_thresholds
        format_suffix: "%"
      - type: gauge
        name: "Temperature"
        measurement: system_hm_1
        field: cpu_temperature
        refresh_rate: 1m
        bounds: [20, 85]
        thresholds: *pi_temp_thresholds
        format_suffix: "°C"
      - type: gauge
        name: "Stockage"
        measurement: system_hm_1
        field: memory_usage
        refresh_rate: 30m
        bounds: [0, 100]
        thresholds: *memory_thresholds
        format_suffix: "%"
  - title: "Pi chambre Thibault"
    influxdb_connector: pizero
    indicators:
      - type: gauge
        name: "CPU"
        measurement: system_hm_2
        field: cpu_usage
        refresh_rate: 1m
        bounds: [0, 100]
        thresholds: *cpu_thresholds
        format_suffix: "%"
      - type: gauge
        name: "Temperature"
        measurement: system_hm_1
        field: cpu_temperature
        refresh_rate: 1m
        bounds: [20, 85]
        thresholds: *pi_temp_thresholds
        format_suffix: "°C"
      - type: gauge
        name: "Stockage"
        measurement: system_hm_1
        field: memory_usage
        refresh_rate: 30m
        bounds: [0, 100]
        thresholds: *memory_thresholds
        format_suffix: "%"


      
